AWSTemplateFormatVersion: "2010-09-09"
Description: Createsa cloudfront distribution for dombff services
Parameters:
  Environment:
    Description: Type of environment
    Type: String
    AllowedValues: [dev, int, uat, prod]
  OriginDomainName:
    Type: String

Resources:
  OriginRequestPolicy:
    Type: AWS::CloudFront::OriginRequestPolicy
    Properties:
      OriginRequestPolicyConfig:
        Name: !Sub '${Environment}-dombff-auth-OriginRequestPolicy'
        CookiesConfig:
          CookieBehavior: 'none'
        HeadersConfig:
          HeaderBehavior: 'none'
        QueryStringsConfig:
          QueryStringBehavior: 'all'
  CommonCachePolicy:
    Type: AWS::CloudFront::CachePolicy
    Properties:
      CachePolicyConfig:
        Name: !Sub '${Environment}-dombff-common-CachePolicy'
        Comment: "Cache Policy for Petstore store resources"
        DefaultTTL: 60
        MaxTTL: 180
        MinTTL: 0
        ParametersInCacheKeyAndForwardedToOrigin:
          CookiesConfig:
            CookieBehavior: 'whitelist'
            Cookies: 
              - atokid
              - patokid
          EnableAcceptEncodingBrotli: true
          EnableAcceptEncodingGzip: true
          HeadersConfig:
            HeaderBehavior: 'whitelist'
            Headers: 
              - Authorization
          QueryStringsConfig:
            QueryStringBehavior: 'all'

  CommonOriginRequestPolicy:
    Type: AWS::CloudFront::OriginRequestPolicy
    Properties:
      OriginRequestPolicyConfig:
        Name: !Sub '${Environment}-dombff-common-OriginRequestPolicy'
        CookiesConfig:
          CookieBehavior: 'none'
        HeadersConfig:
          HeaderBehavior: 'whitelist'
          Headers: 
              - MyCustomPostmanHeader
              - MyCustomPostmanHeader03
        QueryStringsConfig:
          QueryStringBehavior: 'all'

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties: 
      DistributionConfig:
        Origins:
          - Id: originPetstore
            DomainName: !Ref OriginDomainName
            OriginPath: '/dev'
            CustomOriginConfig:
              HTTPSPort: 443
              OriginKeepaliveTimeout: 5
              OriginProtocolPolicy: https-only
              OriginReadTimeout: 30
              OriginSSLProtocols:
                - TLSv1.2
            OriginCustomHeaders: 
              - HeaderName: x-custom-header
                HeaderValue: x-custom-header-value
        HttpVersion: http2
        PriceClass: PriceClass_100
        Enabled: true
        IPV6Enabled: true
        CacheBehaviors:
          - PathPattern: '/dev/store/*'
            TargetOriginId: originPetstore
            CachePolicyId: !Ref CommonCachePolicy
            OriginRequestPolicyId: !Ref CommonOriginRequestPolicy
            ViewerProtocolPolicy: https-only
            AllowedMethods: 
            - GET
            - HEAD
            - OPTIONS
            - PUT
            - POST
            - PATCH
            - DELETE
        DefaultCacheBehavior:
          AllowedMethods: 
            - GET
            - HEAD
          CachePolicyId: '4135ea2d-6df8-44a3-9df3-4b5a84be39ad'
          OriginRequestPolicyId: 'b689b0a8-53d0-40ab-baf2-68738e2966ac'
          TargetOriginId: originPetstore
          ViewerProtocolPolicy: https-only

      Tags: 
        - Key: env
          Value: test